const PRODUCTS = [
  {
    id: "hs-water-gel-hydrator",
    brand: "Her Skin",
    name: "Secret Glow Water Gel Hydrator 50g",
    price: 199,
    image: "assets/products/secret-glow-water-gel-hydrator-50g.jpg",
    sourceUrl: "https://www.herskinph.com/product/secret-glow-water-gel-hydrator-50g/",
    concern: "hydrate",
    badge: "Fresh pick",
    summary: "Lightweight daily hydrator for a soft, dewy finish.",
    details: ["50g jar", "Best for daily moisture", "Pairs well with SPF"]
  },
  {
    id: "hs-brightening-lotion",
    brand: "Her Skin",
    name: "Milk For Skin Double Brightening Lotion",
    price: 280,
    image: "assets/products/milk-for-skin-double-brightening-lotion.png",
    sourceUrl: "https://www.herskinph.com/product/milk-for-skin-double-brightening-lotion/",
    concern: "body-care",
    badge: "Body care",
    summary: "Body lotion for a smooth, brighter-looking glow.",
    details: ["Daily body lotion", "Brightening routine", "Soft milk-inspired finish"]
  },
  {
    id: "hs-facial-cleanser",
    brand: "Her Skin",
    name: "Secret Glow Facial Cleanser 160mL",
    price: 250,
    image: "assets/products/secret-glow-facial-cleanser-160ml.jpg",
    sourceUrl: "https://www.herskinph.com/product/secret-glow-facial-cleanser-160ml/",
    concern: "cleanse",
    badge: "Cleanse",
    summary: "Gentle facial cleanser for everyday glow routines.",
    details: ["160mL bottle", "Daily cleanser", "For morning and evening use"]
  },
  {
    id: "hs-essence-toner",
    brand: "Her Skin",
    name: "Secret Glow Essence Toner 120mL",
    price: 199,
    image: "assets/products/secret-glow-essence-toner-120ml.jpg",
    sourceUrl: "https://www.herskinph.com/product/secret-glow-essence-toner-120ml/",
    concern: "brighten",
    badge: "Glow prep",
    summary: "Essence toner to prep skin before moisturizer.",
    details: ["120mL bottle", "Use after cleansing", "Glow routine essential"]
  },
  {
    id: "hs-body-wash",
    brand: "Her Skin",
    name: "Milk For Skin Body Wash",
    price: 280,
    image: "assets/products/milk-for-skin-body-wash.png",
    sourceUrl: "https://www.herskinph.com/product/milk-for-skin-body-wash/",
    concern: "body-care",
    badge: "Shower care",
    summary: "Creamy body wash for everyday body care.",
    details: ["Body wash", "Milk For Skin line", "Pairs with brightening lotion"]
  },
  {
    id: "hs-bubble-whipp-twin",
    brand: "Her Skin",
    name: "Bubble Whipp Soap Twin Pack",
    price: 239,
    image: "assets/products/bubble-whipp-soap-twin-pack.jpg",
    sourceUrl: "https://www.herskinph.com/product/bubble-whipp-soap-twin-pack/",
    concern: "cleanse",
    badge: "Twin pack",
    summary: "Two-pack soap set for a bubbly cleanse.",
    details: ["Twin pack", "Soap format", "Good for stocking up"]
  },
  {
    id: "hs-bubble-whipp-single",
    brand: "Her Skin",
    name: "Bubble Whipp Soap Single Pack",
    price: 130,
    image: "assets/products/bubble-whipp-soap-single-pack.jpg",
    sourceUrl: "https://www.herskinph.com/product/bubble-whipp-soap-single-pack/",
    concern: "cleanse",
    badge: "Single",
    summary: "Single Bubble Whipp soap for daily cleansing.",
    details: ["Single pack", "Soap format", "Easy routine starter"]
  },
  {
    id: "hs-tone-up-cream",
    brand: "Her Skin",
    name: "Secret Glow Tone-up Cream 50g",
    price: 220,
    image: "assets/products/secret-glow-tone-up-cream-50g.jpg",
    sourceUrl: "https://www.herskinph.com/product/secret-glow-tone-up-cream-50g/",
    concern: "brighten",
    badge: "Tone up",
    summary: "Tone-up cream for a brighter-looking finish.",
    details: ["50g tube", "Use after skin prep", "Brightening finish"]
  },
  {
    id: "hs-secret-glow-set",
    brand: "Her Skin",
    name: "Secret Glow",
    price: 399,
    image: "assets/products/secret-glow.jpg",
    sourceUrl: "https://www.herskinph.com/product/secret-glow/",
    concern: "brighten",
    badge: "Routine set",
    summary: "Secret Glow routine set for a complete skin care flow.",
    details: ["Set format", "Glow routine", "Best for gifting"]
  },
  {
    id: "hs-spf45",
    brand: "Her Skin",
    name: "Sun Defense SPF45 50g",
    price: 180,
    image: "assets/products/sun-defense-spf45-50g.png",
    sourceUrl: "https://www.herskinph.com/product/sun-defense-spf45-50g/",
    concern: "sun-care",
    badge: "SPF 45",
    summary: "Daily sun defense in a 50g size.",
    details: ["50g tube", "SPF45", "Daytime essential"]
  },
  {
    id: "hs-spf30",
    brand: "Her Skin",
    name: "Sun Defense SPF 30 20g",
    price: 100,
    image: "assets/products/sun-defense-spf-30-20g.png",
    sourceUrl: "https://www.herskinph.com/product/sun-defense-spf-30-20g/",
    concern: "sun-care",
    badge: "Travel size",
    summary: "Compact SPF 30 for daily carry.",
    details: ["20g tube", "SPF30", "Easy to pack"]
  },
  {
    id: "hs-kojic-collagen",
    brand: "Her Skin",
    name: "Premium Kojic Collagen Soap",
    price: 120,
    image: "assets/products/premium-kojic-collagen-soap.png",
    sourceUrl: "https://www.herskinph.com/product/premium-kojic-collagen-soap/",
    concern: "brighten",
    badge: "Soap",
    summary: "Kojic collagen soap for a brightening cleanse.",
    details: ["Soap bar", "Kojic collagen", "Brightening routine"]
  },
  {
    id: "hs-night-gel",
    brand: "Her Skin",
    name: "Revitalizing Night Gel Cream",
    price: 80,
    image: "assets/products/revitalizing-night-gel-cream.png",
    sourceUrl: "https://www.herskinph.com/product/revitalizing-night-gel-cream/",
    concern: "hydrate",
    badge: "Night care",
    summary: "Light night gel cream for bedtime skin care.",
    details: ["Night cream", "Gel texture", "Use after toner"]
  },
  {
    id: "hs-revitalizing-toner",
    brand: "Her Skin",
    name: "Revitalizing Toner",
    price: 90,
    image: "assets/products/revitalizing-toner.png",
    sourceUrl: "https://www.herskinph.com/product/revitalizing-toner/",
    concern: "brighten",
    badge: "Toner",
    summary: "Revitalizing toner for simple daily prep.",
    details: ["Toner", "Daily prep", "Budget-friendly routine add-on"]
  },
  {
    id: "hs-revita-glow",
    brand: "Her Skin",
    name: "Revita-Glow Skin Rescue",
    price: 349,
    image: "assets/products/revita-glow-skin-rescue.png",
    sourceUrl: "https://www.herskinph.com/product/revita-glow-skin-rescue/",
    concern: "brighten",
    badge: "Bestseller",
    summary: "Skin rescue kit for a brighter daily glow routine.",
    details: ["Kit format", "Glow routine", "Community favorite"]
  },
  {
    id: "neco-nekothione",
    brand: "Neco",
    name: "Nekothione",
    price: 600,
    image: "assets/products/neko-nekothione.jpg",
    sourceUrl: "#",
    concern: "wellness",
    badge: "9 in 1",
    summary: "A beauty supplement designed for daily glow support from within.",
    details: ["Food supplement", "14 capsules", "Made for beauty and wellness routines"]
  },
  {
    id: "sevendays-power-exfoliating-set",
    brand: "Sevendays",
    name: "Power Exfoliating Set",
    price: 300,
    image: "assets/products/sevendays-power-exfoliating-set.jpg",
    sourceUrl: "#",
    concern: "body-care",
    badge: "Exfoliating set",
    summary: "A bright blue care set for smoothing, polishing, and refreshing weekly skin routines.",
    details: ["Multi-piece exfoliating set", "Includes care pouch", "Designed for weekly skin reset rituals"]
  }
];
